### ISSUE TITLE
I believe "ungles" should be tagged as Latin instead of French.

### ISSUE THREAD

**Issue by kingrpaul** [kingrpaul/apuleius_the-golden-ass-of-apuleius_william-adlington#3]

**Comment by kingrpaul** [comment]
@EmmaSweeney, Whibley describes "ungles" as an expressive translation from Latin and the Latin version uses words with root "ungu-" e.g. "ungulis". So, this looks like a translation from Latin into French, which the translator believes to be English but which does not appear in Merriam-Webster.   👍?

**Comment by EmmaSweeney** [comment]
Ok, you can keep it the same.
