### ISSUE TITLE
Sylla does not need italics or a language tag. The "the time of Sylla" refers to the reign of Lucius Cornelius Sulla (commonly known as Sulla or Sylla).

### ISSUE THREAD

**Issue by kingrpaul** [kingrpaul/apuleius_the-golden-ass-of-apuleius_william-adlington#4]

**Comment by kingrpaul** [comment]
@EmmaSweeney: The original scans spell the name “Silla” which I believe refers to Sulla, though Apuleius writes in the first person in the “time of Silla,” and Sulla died two centuries before he was born. Maybe he refers to some other Sulla, in Greece or Carthage? Merriam Webster and Wikipedia show “Silla” as a thousand-year kingdom in Korea, so I don’t want to leave it. The Gaselee revision of Apuleius spells the name“Sylla” (“Syllae” untranslated).  Merriam-Webster does not recognize “Sylla” as English. Wikipedia shows it to be the last name of many modern French-speaking people.  Also as the “French name for Lucius Cornelius Sulla, a Roman general and statesman.” Again, there’s Whibley’s remarks about Adlington’s reliance on the French. So, I’ve changed “Silla” to “Sylla” and marked it as French in a span. It was not immediately obvious to me that Silla was Sulla., I think the language marking may be useful to the ebook reader (and app) and hope you agree.

**Comment by EmmaSweeney** [comment]
Ok, that's fine. Keep in mind that proper names won't appear in Merriam-Webster's dictionary.
