### ISSUE TITLE
The files publishers-introduction.xhtml, tramslators-introduction-1.xhtml, tramslators-introduction-2.xhtml, and translators-dedication.xhtml actually look like they are forewards. They are not written by the author, they cover various subjects around this book, and they are located before the author's preface.

### ISSUE THREAD

**Issue by kingrpaul** [kingrpaul/apuleius_the-golden-ass-of-apuleius_william-adlington#5]

**Comment by kingrpaul** [comment]
@EmmaSweeney: This is produces a lint error s-032: Invalid value for epub:type attribute.  As best I can tell, it is not invalid. I looked for a completed work to compare against but did not find any that included a "foreward".

**Comment by EmmaSweeney** [comment]
I'm sorry! I misspelled it! it should be "foreword," not "foreward". I recommend checking file semantics from the [EPUB 3 Structural Semantics Vocabulary](https://idpf.github.io/epub-vocabs/structure/).

**Comment by kingrpaul** [comment]
Thanks. That got it. I'd looked it up and did the same. Those 3 spellings seem to blend together.
06d1ae20e6d78c8c88a1a2a0370e76e3c71ea667
